### ISSUE TITLE
All downloading broken?

### ISSUE THREAD

**Issue by ElgarL** [Tenpi/Crunchyroll-Downloader#84]
https://www.crunchyroll.com/series/GVDHX8JJE/black-summoner

gives error (yes I'm logged in).

renderer.js:43          GET https://www.crunchyroll.com/index/v2 401
K @ renderer.js:43
await in K (async)
(anonymous) @ renderer.js:43
ee @ renderer.js:43
await in ee (async)
X @ renderer.js:43
de @ renderer.js:43
He @ renderer.js:19
Ze @ renderer.js:19
(anonymous) @ renderer.js:19
Rn @ renderer.js:19
Pn @ renderer.js:19
(anonymous) @ renderer.js:19
Le @ renderer.js:19
(anonymous) @ renderer.js:19
Ln @ renderer.js:19
er @ renderer.js:19
Xt @ renderer.js:19
t.unstable_runWithPriority @ renderer.js:43
Zo @ renderer.js:19
De @ renderer.js:19
Jt @ renderer.js:19
renderer.js:43 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'policy')
    at K (renderer.js:43:237203)
    at async renderer.js:43:244311
    at async ee (renderer.js:43:243900)

**Comment by Tenpi** [comment]
Can you try a logout and login again.

**Comment by ElgarL** [comment]
After log out/in

trying to DL "In another world with my smartphone" at 720p
![image](https://github.com/Tenpi/Crunchyroll-Downloader/assets/898636/2a11bb6f-7e80-4642-ae9e-ba23639ab48a)
The downloads propagate but none start.

**Comment by Tenpi** [comment]
The app has a "Delete Cookies" option in advanced settings, can you try pressing that and logging in again? Also are you using the search bar or browser

**Comment by ElgarL** [comment]
Clearing cookies stopped all the 401 errors, however nothing is downloading.

**Comment by ElgarL** [comment]
Just tried using search with same results. All vids queue but nothing downloads. No errors in console

https://www.crunchyroll.com/series/GYQ4ZWV46/in-another-world-with-my-smartphone

**Comment by Tenpi** [comment]
Do any of the formats download? Do you have any strange characters or punctuation in the name of the destination folder?

**Comment by Tenpi** [comment]
And you are sure this drive has writing permissions enabled (for regular users, not admin)? I don't have any issues, but tell me the oldest version that works if any, I will see what I changed

**Comment by Tenpi** [comment]
Maybe you have issues because you used a version I deleted can you try uninstalling and reinstalling again (there should be an uninstaller in the location you installed the application)

**Comment by ElgarL** [comment]
I don't think it has actually created a vid file since I updated to 0.6.8. I just assumed that was because it was a network drive, even though it has full write access (I was going to mention network drives in another post). It clearly creates folders and writes .ass files.
I'll try a full clean install of current build.

**Comment by ElgarL** [comment]
Uninstall/reinstall same result. It creates the correct folders, downloads and saves the .ass subtitle files, but all vids just queue up and never download.
v0.7.1

**Comment by Tenpi** [comment]
Probably because I updated ffmpeg once again your OS is probably too old and unsupported; I will try downgrading to the previous version

**Comment by Tenpi** [comment]
Tell me if `v0.7.2` works. You can also delete the ffmpeg installed with the program and it will call `ffmpeg` from your PATH instead. If that one doesn't work you can post an ffmpeg version that works on your machine here

**Comment by ElgarL** [comment]
0.7.2 breaks on Win 10

renderer.js:43 Uncaught (in promise) TypeError: e.includes is not a function
    at Ae.convertSeconds (renderer.js:43:40004)
    at Y (renderer.js:43:240528)
    at async ee (renderer.js:43:245575)

Under Win 7 It's not changed. Downloads and creates all teh .ass files but no progress on vids. I'll try different ffmpeg.

**Comment by Tenpi** [comment]
Has this software ever worked for you on Win7 or did you switch to it recently? You can find even older versions here, although I don't recommend going too old since it may not have the features I'm using. 

https://www.ffmpeg.org/olddownload.html 

As for the Win10 error it can be fixed by changing "Trim Start" field to anything, but I will publish the fix in the next version.

**Comment by ElgarL** [comment]
I'd been using it for ages on Win 7. It's all I've ever run it on. Version 0.6.1
I can;t get anything working on Win 7 or Win 10 now. I uninstalled on Win 10 and even deleted all in %appdata%

**Comment by Tenpi** [comment]
Huh, well you don't see any errors because it's occurring in the main process where it calls ffmpeg, I will have to improve error logging. Do mkv downloads also not work?

**Comment by ElgarL** [comment]
Nope to MKV

**Comment by Tenpi** [comment]
download 0.7.3 hopefully you can see the errors

**Comment by ElgarL** [comment]
renderer.js:43 [error] Filtergraph 'ass='I\:\\Anime Downloads/One Piece/One Piece East Blue (1 61)/E5 - A Terrifying Mysterious Power! Captain Buggy the Clown Pirate!.ass'' was defined for video output stream 0:0 but codec copy was selected.
t @ renderer.js:43
emit @ node:events:513
onMessage @ node:electron/js2c/renderer_init:2
renderer.js:43 Error: FFmpeg exited with code 1
    at s (D:\Program Files\Crunchyroll Downloader\resources\app.asar\dist\main.js:28:21948)
    at ChildProcess.o (D:\Program Files\Crunchyroll Downloader\resources\app.asar\dist\main.js:28:22175)
    at ChildProcess.emit (node:events:525:35)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12)
t @ renderer.js:43
emit @ node:events:513
onMessage @ node:electron/js2c/renderer_init:2
renderer.js:43 (25) ['-y', '-progress', 'pipe:1', '-nostats', '-loglevel', '+repeat+level+error', '-user_agent', 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:124.0) Gecko/20100101 Firefox/124.0', '-i', 'https://pl.crunchyroll.com/evs3/058e07c004ed57e3d9…oLm2FOFXY2cbGg__&Key-Pair-Id=APKAJMWSQ5S7ZB3MF5VA', '-i', 'I:/Anime Downloads/One Piece/One Piece East Blue (…erious Power! Captain Buggy the Clown Pirate!.ass', '-vf', "ass='I\\:\\\\Anime Downloads/One Piece/One Piece East…rious Power! Captain Buggy the Clown Pirate!.ass'", '-c', 'copy', '-bsf:a', 'aac_adtstoasc', '-crf', '23', '-pix_fmt', 'yuv420p', '-movflags', '+faststart', 'I:/Anime Downloads/One Piece/One Piece East Blue (…erious Power! Captain Buggy the Clown Pirate!.mp4']

**Comment by Tenpi** [comment]
Oh, you have to set the video codec to H.264 (or anything other than "No Re-Encoding") because re-encoding the video is required for mp4 in order to burn the subtitles in. You can select no re-encode only if you download mkv (soft subtitles).

**Comment by ElgarL** [comment]
So thats something you have to do? as I have no control over that, other than select MKV which I hate using due to having to re-encode after.

**Comment by Tenpi** [comment]
I had to do that in order to change the font size/color/y position of the subtitles. 

If you want to download mp4 without re-encoding I can think of two options, either I download the default hard sub from CR (this was what the old downloader did) or I try to add the modified subtitles as soft subs. I'm not sure if mp4 supports soft subtitles so I have to look into it.

**Comment by ElgarL** [comment]
https://stackoverflow.com/questions/8672809/use-ffmpeg-to-add-text-subtitles/17584272#17584272

**Comment by Tenpi** [comment]
Added the subtitles as soft subs in 0.7.4 (do note that you need to use a player that supports soft subs or you won't see anything).

**Comment by ElgarL** [comment]
Seems to be working so Closing for now.
